### ISSUE TITLE
Training failed on TPUs for Dreambooth

### ISSUE THREAD

**Issue by StateGovernment** [entrpn/serving-model-cards#8]
Followed all instructions by the book, had images in a local images folder as-well. Training job stopped after 6 minutes with an error "replica workerpool0-0 exited with a non-zero status of 1", I had a TPU quota of 25 so they wouldn't run out as-well.

Screenshot of the Training Job from Console.
<img width="1332" alt="Screenshot 2023-03-17 at 2 33 09 AM" src="https://user-images.githubusercontent.com/82204226/225752207-da71d9c4-d291-4573-b48d-5504c16a43d6.png">

Here's a csv of logs for reference.
[downloaded-logs-20230317-023353.csv](https://github.com/entrpn/serving-model-cards/files/10995841/downloaded-logs-20230317-023353.csv)

CLI command I've used to trigger the job.
`python3.8 gcp_run_train.py --project-id=dreamboothtest --region=us-central1 --image-uri=gcr.io/dreamboothtest/training-dreambooth:latest --gcs-output-dir=gs://dreamboothmodelstore --instance-prompt="a photo of qw23 person" --hf-token="<>" --class-prompt="A photo of a person" --max-train-steps=800`

please help

**Comment by entrpn** [comment]
@StateGovernment I updated the repo, please pull it and try again.

**Comment by StateGovernment** [comment]
@entrpn Training works perfectly with the new version, thank you. Although the environment needed to run inferencing on TPU is not provided as of now, I am trying to assume environment from DockerFile given, but hasn't been successful yet. Could you also please freeze your pip and provide a requirements file just for Inferencing through Jax on TPU. 

This is the error I get for inferencing on Colab, for reference.
<img width="1055" alt="Screenshot 2023-03-20 at 11 35 53 AM" src="https://user-images.githubusercontent.com/82204226/226260097-1e85acf4-5a28-437e-bcd6-f1c55fc8667c.png">

Thank you so much for the training fix, closing this now as this was a training specific issue fixed.

**Comment by entrpn** [comment]
@StateGovernment I haven't tested on colab. Try running the following with a GPU colab environment or in a Vertex AI Workbench notebook with a T4 GPU (this is my environment).

1. Copy your model to `model` folder in colab or workbench.
2. Install dependencies

```bash
transformers==4.27.1
diffusers==0.14.0
jax==0.3.25
jaxlib==0.3.25
flax==0.6.4
torch==1.13.1
```

4. Call the script:

```python
from diffusers import StableDiffusionPipeline
import torch
import jax

pipe = StableDiffusionPipeline.from_pretrained("./model", safety_checker=None, from_flax=True, dtype=torch.float16).to("cuda")

prompt = "a photo of sks man wearing a suit and sunglasses, highly detailed, close up shot"
negative_prompt="rendered, unrealistic, work of art, artistic, cinematic"

image = pipe(prompt,negative_prompt=negative_prompt).images[0]

image.save("output.png")
```

This script will automatically convert flax/jax weights to torch and run inference. If you want to save the weights in torch format, just run:

```python
from diffusers import StableDiffusionPipeline
import torch
import jax

pipe = StableDiffusionPipeline.from_pretrained("./model", safety_checker=None, from_flax=True, dtype=torch.float16).to("cuda")

# Save torch weights
pipe.save_pretrained("model_torch")
```

Then you can load the pytorch model directly, instead of converting it every time you run the script with a GPU.

`pipe = StableDiffusionPipeline.from_pretrained("./model_torch", safety_checker=None, dtype=torch.float16).to("cuda")`

**Comment by StateGovernment** [comment]
@entrpn I have a few questions on the training flow which are extremely crucial for our pipeline, can I upload images of different subjects each time I call `gcp_run_train.py` on step 4?

At which point do the images get uploaded for the training job? 
If the images actually get uploaded while building the container and pushing it? In that case do I have to build a new training container each time I want to train dreambooth on a different subject?

**Comment by StateGovernment** [comment]
This is working perfectly, all I need to pass to is a gcs bucket address with training images, I am also assuming we can eliminate the need to download a model from Hugging face by pushing the model within the container itself, thus saving a few more seconds in a similar way.

Thank you for the guidance Juan.
